version: "3.7"

services:
  kdc:
    build:
      context: ./
      dockerfile: ./kdc/Dockerfile
    image: kdc:0.1
    container_name: kdc
    hostname: kdc
    domainname: linux.contoso.com
    dns_search: linux.contoso.com
    volumes:
      - shared-volume:/SHARED
    networks:
      - network1

  linuxweb:
    build:
      context: ./
      dockerfile: ./linuxweb/Dockerfile
    image: linuxweb:0.1
    container_name: linuxweb
    hostname: linuxweb
    domainname: linux.contoso.com
    dns_search: linux.contoso.com
    volumes:
      - shared-volume:/SHARED
    networks:
      network1:
        aliases:
          - webserver.linux.contoso.com
    depends_on:
      - kdc

  apacheweb:
    build:
      context: ./
      dockerfile: ./apacheweb/Dockerfile
    image: apacheweb:0.1
    container_name: apacheweb
    hostname: apacheweb
    domainname: linux.contoso.com
    dns_search: linux.contoso.com
    volumes:
      - shared-volume:/SHARED
    networks:
      network1:
        aliases:
          - apache.linux.contoso.com
    depends_on:
      - kdc

  linuxclient:
    build:
      context: ./
      dockerfile: ./linuxclient/Dockerfile
      args:
        SDK_BASE_IMAGE: sdk-corefx-current:5.0
    image: linuxclient:0.1
    container_name: linuxclient
    hostname: linuxclient
    domainname: linux.contoso.com
    dns_search: linux.contoso.com
    volumes:
      - shared-volume:/SHARED
    networks:
      - network1
    depends_on:
      - apacheweb
      - linuxweb
      - kdc

networks:
  network1:
    name: linux.contoso.com

volumes:
  shared-volume:
