version: "3.7"

services:
  kdc:
    build:
      context: ./
      dockerfile: ./kdc/Dockerfile
    image: kdc:0.1
    container_name: kdc
    hostname: kdc
    domainname: linux.contoso.com
    dns_search: linux.contoso.com
    volumes:
      - shared-volume:/keytabs
    networks:
      - network1

  linuxclient:
    build:
      context: ./
      dockerfile: ./linuxclient/Dockerfile
    image: linuxclient:0.1
    container_name: linuxclient
    hostname: linuxclient
    domainname: linux.contoso.com
    dns_search: linux.contoso.com
    networks:
      - network1
    depends_on:
      - linuxweb
      - kdc

  linuxweb:
    build:
      context: ./
      dockerfile: ./linuxweb/Dockerfile
    image: linuxweb:0.1
    container_name: linuxweb
    hostname: linuxweb
    domainname: linux.contoso.com
    dns_search: linux.contoso.com
    volumes:
      - shared-volume:/keytabs
    networks:
      network1:
        aliases:
          - webserver.linux.contoso.com
    depends_on:
      - kdc

networks:
  network1:
    name: linux.contoso.com

volumes:
  shared-volume:
